name: encrypt secret
description: 重新加密secret使得其可以跨job传递


inputs:
  VALUE:
    type: string
    required: true
  SECRET_PASSING_KEY:
    type: string
    required: true

outputs:
  ENCRYPTED_VALUE:
    value: ${{ steps.encrypt-app-token.outputs.ENCRYPTED_VALUE }}


runs:
  using: composite
  steps:
    - name: encrypt
      id: encrypt-app-token
      run: |
        result=$(gpg --symmetric --batch --passphrase "${{ inputs.SECRET_PASSING_KEY }}" --output - <(echo "${{ inputs.VALUE }}") | base64 -w0)
        echo "ENCRYPTED_VALUE=$result" >> $GITHUB_OUTPUT
      shell: bash
