name: 生成安装访问令牌

inputs:
  APP_ID:
    type: string
    required: true
  APP_PRIVATE_KEY:
    type: string
    required: true
  SECRET_PASSING_KEY:
    type: string
    required: true

outputs:
  APP_TOKEN:
    value: ${{ steps.gen-app-token.outputs.APP_TOKEN }}
  ENCRYPTED_TOKEN:
    value: ${{ steps.gen-app-token.outputs.ENCRYPTED_VALUE }}


runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18 # node版本
    - run: npm i @octokit/rest @octokit/auth-app @actions/core
      shell: bash
    - env:
        SCRIPT_CONTENT: |
          import * as core from '@actions/core';
          import { Octokit } from "@octokit/rest";
          import { createAppAuth } from "@octokit/auth-app";
          
          const appOctokit = new Octokit({ authStrategy: createAppAuth, auth: { appId: '${{ inputs.APP_ID }}', privateKey: `${{ inputs.APP_PRIVATE_KEY }}` } });
          const installation = await appOctokit.rest.apps.getOrgInstallation({ org: '${{ github.repository_owner }}' });
          const result = await appOctokit.rest.apps.createInstallationAccessToken({ installation_id: installation.data.id });
          const token = result.data.token;
          core.setSecret(token);
          core.setOutput('APP_TOKEN', token);
      run: echo "$SCRIPT_CONTENT" >> generate-token.mjs
      shell: bash
    - id: gen-app-token
      run: node generate-token.mjs
      shell: bash
    - id: encrypt-app-token
      uses: Enraged-Dun-Cookie-Development-Team/Ceobe-Github-Bot/actions/encrypt-secret@master
      with:
        VALUE: ${{ steps.gen-app-token.outputs.APP_TOKEN }}
        SECRET_PASSING_KEY: ${{ inputs.SECRET_PASSING_KEY }}
